//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.00:00:00")]
        public global::System.TimeSpan ResetPasswordTTL {
            get {
                return ((global::System.TimeSpan)(this["ResetPasswordTTL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44300/")]
        public string BaseUrl {
            get {
                return ((string)(this["BaseUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(i dev)")]
        public string MailSuffix {
            get {
                return ((string)(this["MailSuffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dev")]
        public string Environment {
            get {
                return ((string)(this["Environment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("unknown")]
        public string DeploymentVersion {
            get {
                return ((string)(this["DeploymentVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("arne123")]
        public string DefaultUserPassword {
            get {
                return ((string)(this["DefaultUserPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string UseDefaultPassword {
            get {
                return ((string)(this["UseDefaultPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5a96f4868fb67ef4829a91588a0cf0de4d2290ea")]
        public string SsoCertificateThumbprint {
            get {
                return ((string)(this["SsoCertificateThumbprint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://kitos-local.strongminds.dk")]
        public string SsoServiceProviderId {
            get {
                return ((string)(this["SsoServiceProviderId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://adgangsstyring.eksterntest-stoettesystemerne.dk/")]
        public string StsIssuer {
            get {
                return ((string)(this["StsIssuer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://adgangsstyring.eksterntest-stoettesystemerne.dk/runtime/services/kombittr" +
            "ust/14/certificatemixed")]
        public string StsCertificateEndpoint {
            get {
                return ((string)(this["StsCertificateEndpoint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eksterntest-stoettesystemerne.dk")]
        public string StsOrganisationEndpointHost {
            get {
                return ((string)(this["StsOrganisationEndpointHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ORG_EXTTEST_Organisation_1")]
        public string ServiceCertificateAliasOrg {
            get {
                return ((string)(this["ServiceCertificateAliasOrg"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADG_EXTTEST_Adgangsstyring_1")]
        public string StsCertificateAlias {
            get {
                return ((string)(this["StsCertificateAlias"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0aa7a193f18d095f7e2ce09d892178c9682b7924")]
        public string StsCertificateThumbprint {
            get {
                return ((string)(this["StsCertificateThumbprint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://organisation.eksterntest-stoettesystemerne.dk/service/organisation/3")]
        public string OrgService6EntityId {
            get {
                return ((string)(this["OrgService6EntityId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://organisation.eksterntest-stoettesystemerne.dk/organisation/virksomhed/6")]
        public string StsVirksomhedPort {
            get {
                return ((string)(this["StsVirksomhedPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://organisation.eksterntest-stoettesystemerne.dk/organisation/organisation/6" +
            "")]
        public string StsOrganisationPort {
            get {
                return ((string)(this["StsOrganisationPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://organisation.eksterntest-stoettesystemerne.dk/organisation/organisationsy" +
            "stem/6")]
        public string StsOrganisationSystemPort {
            get {
                return ((string)(this["StsOrganisationSystemPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2c34be56b35d993160df525c36146336ea2b2801")]
        public string StsOrganisationCertificateThumbprint {
            get {
                return ((string)(this["StsOrganisationCertificateThumbprint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://organisation.eksterntest-stoettesystemerne.dk/organisation/adresse/6")]
        public string StsAdressePort {
            get {
                return ((string)(this["StsAdressePort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://organisation.eksterntest-stoettesystemerne.dk/organisation/bruger/6")]
        public string StsBrugerPort {
            get {
                return ((string)(this["StsBrugerPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://organisation.eksterntest-stoettesystemerne.dk/organisation/person/6")]
        public string StsPersonPort {
            get {
                return ((string)(this["StsPersonPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:7226/")]
        public string PubSubBaseUrl {
            get {
                return ((string)(this["PubSubBaseUrl"]));
            }
        }
    }
}
