// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/ui-select/ui-select.d.ts
declare module "ui-select" {
    var _: string;
    export = _;
}

declare namespace angular.ui.select {
    interface ISelectConfig {
        appendToBody: boolean;
        resetSearchInput: boolean;
        theme: string;
    }
}
