<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
    name="OrganisationAdministrationService"
    targetNamespace="http://stoettesystemerne.dk/organisation/6/"
    xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns="http://stoettesystemerne.dk/organisation/6/"
    xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
    xmlns:wsp="http://www.w3.org/ns/ws-policy"
    xmlns:type="http://stoettesystemerne.dk/organisation/organisationadministration/6/"
    xmlns:header="http://kombit.dk/xml/schemas/RequestHeader/1/">

  <wsdl:import namespace="http://serviceplatformen.dk/xml/wsdl/soap11/Security/Policy"
               location="policies/OIOIDWS.wsdl"/>
  
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://stoettesystemerne.dk/organisation/organisationadministration/6/" schemaLocation="../xsd/6.0.STS-0/OrganisationAdministrationOperationer.xsd"/>
      <xsd:import namespace="http://kombit.dk/xml/schemas/RequestHeader/1/" schemaLocation="../xsd/common/RequestHeader.xsd" />
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="FysiskSletRequestMessage">
    <wsdl:part name="header" element="header:RequestHeader"/>
    <wsdl:part name="request" element="type:FysiskSletInput">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="FysiskSletResponseMessage">
    <wsdl:part name="header" element="header:RequestHeader"/>
    <wsdl:part name="response" element="type:FysiskSletOutput">
    </wsdl:part>
  </wsdl:message>

  <wsdl:portType name="OrganisationAdministrationPortType">
    <wsdl:operation name="fysiskslet">
      <wsdl:input message="tns:FysiskSletRequestMessage">
      </wsdl:input>
      <wsdl:output message="tns:FysiskSletResponseMessage">
      </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="OrganisationAdministration" type="tns:OrganisationAdministrationPortType">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsp:PolicyReference URI="#ServiceplatformBindingPolicy"/>
    <wsdl:operation name="fysiskslet">
      <soap12:operation soapAction="http://kombit.dk/sts/organisation/organisationadministration/fysiskslet" soapActionRequired="false"/>
      <wsdl:input>
        <soap12:header message="tns:FysiskSletRequestMessage" part="header" use="literal"/>
        <soap12:body parts="request" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:header message="tns:FysiskSletResponseMessage" part="header" use="literal"/>
        <soap12:body parts="response" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="OrganisationAdministrationService">
    <wsdl:port name="OrganisationAdministration" binding="tns:OrganisationAdministration">
      <soap12:address location="http://kombit.dk/sts/organisation/organisationadministration"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>
