/// <reference path="JSONfn/index.d.ts" />
/// <reference path="kendo/index.d.ts"/>
/// <reference path="protractor-http-mock/index.d.ts"/>
/// <reference path="jquery/index.d.ts"/>
/// <reference path="angular-animate/index.d.ts" />
/// <reference path="angular-cookies/index.d.ts" />
/// <reference path="angular-mocks/index.d.ts" />
/// <reference path="angular-protractor/index.d.ts" />
/// <reference path="angular-resource/index.d.ts" />
/// <reference path="angular-ui-bootstrap/index.d.ts" />
/// <reference path="angular-ui-router/index.d.ts" />
/// <reference path="angular/index.d.ts" />
/// <reference path="jasmine-expect/index.d.ts" />
/// <reference path="jasmine/index.d.ts" />
/// <reference path="lodash/index.d.ts" />
/// <reference path="moment/index.d.ts" />
/// <reference path="selenium-webdriver/index.d.ts" />
/// <reference path="ui-select/index.d.ts" />
