//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kombit.InfrastructureSamples.VirksomhedService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://stoettesystemerne.dk/organisation/6/", ConfigurationName="Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType")]
    public interface VirksomhedPortType
    {
        
        // CODEGEN: Generating message contract since the operation opret is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/opret", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        Kombit.InfrastructureSamples.VirksomhedService.opretResponse opret(Kombit.InfrastructureSamples.VirksomhedService.opretRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/opret", ReplyAction="*")]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.opretResponse> opretAsync(Kombit.InfrastructureSamples.VirksomhedService.opretRequest request);
        
        // CODEGEN: Generating message contract since the operation importer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/importer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        Kombit.InfrastructureSamples.VirksomhedService.importerResponse importer(Kombit.InfrastructureSamples.VirksomhedService.importerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/importer", ReplyAction="*")]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.importerResponse> importerAsync(Kombit.InfrastructureSamples.VirksomhedService.importerRequest request);
        
        // CODEGEN: Generating message contract since the operation passiver is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/passiver", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        Kombit.InfrastructureSamples.VirksomhedService.passiverResponse passiver(Kombit.InfrastructureSamples.VirksomhedService.passiverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/passiver", ReplyAction="*")]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.passiverResponse> passiverAsync(Kombit.InfrastructureSamples.VirksomhedService.passiverRequest request);
        
        // CODEGEN: Generating message contract since the operation laes is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/laes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        Kombit.InfrastructureSamples.VirksomhedService.laesResponse laes(Kombit.InfrastructureSamples.VirksomhedService.laesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/laes", ReplyAction="*")]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.laesResponse> laesAsync(Kombit.InfrastructureSamples.VirksomhedService.laesRequest request);
        
        // CODEGEN: Generating message contract since the operation ret is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/ret", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        Kombit.InfrastructureSamples.VirksomhedService.retResponse ret(Kombit.InfrastructureSamples.VirksomhedService.retRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/ret", ReplyAction="*")]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.retResponse> retAsync(Kombit.InfrastructureSamples.VirksomhedService.retRequest request);
        
        // CODEGEN: Generating message contract since the operation slet is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/slet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        Kombit.InfrastructureSamples.VirksomhedService.sletResponse slet(Kombit.InfrastructureSamples.VirksomhedService.sletRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/slet", ReplyAction="*")]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.sletResponse> sletAsync(Kombit.InfrastructureSamples.VirksomhedService.sletRequest request);
        
        // CODEGEN: Generating message contract since the operation soeg is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/soeg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        Kombit.InfrastructureSamples.VirksomhedService.soegResponse soeg(Kombit.InfrastructureSamples.VirksomhedService.soegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/soeg", ReplyAction="*")]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.soegResponse> soegAsync(Kombit.InfrastructureSamples.VirksomhedService.soegRequest request);
        
        // CODEGEN: Generating message contract since the operation list is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/list", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        Kombit.InfrastructureSamples.VirksomhedService.listResponse list(Kombit.InfrastructureSamples.VirksomhedService.listRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/organisation/virksomhed/list", ReplyAction="*")]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.listResponse> listAsync(Kombit.InfrastructureSamples.VirksomhedService.listRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
    public partial class RequestHeaderType
    {
        
        private string transactionUUIDField;
        
        /// <remarks/>
        public string TransactionUUID
        {
            get
            {
                return this.transactionUUIDField;
            }
            set
            {
                this.transactionUUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class ListInputType
    {
        
        private string[] uUIDIdentifikatorField;
        
        private TidspunktType virkningFraFilterField;
        
        private TidspunktType virkningTilFilterField;
        
        private TidspunktType registreringFraFilterField;
        
        private TidspunktType registreringTilFilterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UUIDIdentifikator", Order=0)]
        public string[] UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType VirkningFraFilter
        {
            get
            {
                return this.virkningFraFilterField;
            }
            set
            {
                this.virkningFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TidspunktType VirkningTilFilter
        {
            get
            {
                return this.virkningTilFilterField;
            }
            set
            {
                this.virkningTilFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TidspunktType RegistreringFraFilter
        {
            get
            {
                return this.registreringFraFilterField;
            }
            set
            {
                this.registreringFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TidspunktType RegistreringTilFilter
        {
            get
            {
                return this.registreringTilFilterField;
            }
            set
            {
                this.registreringTilFilterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class TidspunktType
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GraenseIndikator", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TidsstempelDatoTid", typeof(System.DateTime), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegOutputType
    {
        
        private StandardReturType standardReturField;
        
        private string[] idListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StandardReturType StandardRetur
        {
            get
            {
                return this.standardReturField;
            }
            set
            {
                this.standardReturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("UUIDIdentifikator", IsNullable=false)]
        public string[] IdListe
        {
            get
            {
                return this.idListeField;
            }
            set
            {
                this.idListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnikReturType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class StandardReturType
    {
        
        private string statusKodeField;
        
        private string fejlbeskedTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string StatusKode
        {
            get
            {
                return this.statusKodeField;
            }
            set
            {
                this.statusKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FejlbeskedTekst
        {
            get
            {
                return this.fejlbeskedTekstField;
            }
            set
            {
                this.fejlbeskedTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UnikReturType : StandardReturType
    {
        
        private string typeField;
        
        private string uUIDIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegVirkningType
    {
        
        private TidspunktType fraTidspunktField;
        
        private TidspunktType tilTidspunktField;
        
        private UnikIdType aktoerRefField;
        
        private AktoerTypeKodeType aktoerTypeKodeField;
        
        private bool aktoerTypeKodeFieldSpecified;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType TilTidspunkt
        {
            get
            {
                return this.tilTidspunktField;
            }
            set
            {
                this.tilTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UnikIdType AktoerRef
        {
            get
            {
                return this.aktoerRefField;
            }
            set
            {
                this.aktoerRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AktoerTypeKodeType AktoerTypeKode
        {
            get
            {
                return this.aktoerTypeKodeField;
            }
            set
            {
                this.aktoerTypeKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AktoerTypeKodeSpecified
        {
            get
            {
                return this.aktoerTypeKodeFieldSpecified;
            }
            set
            {
                this.aktoerTypeKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UuidLabelInputType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UnikIdType
    {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("URNIdentifikator", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UUIDIdentifikator", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0", IncludeInSchema=false)]
    public enum ItemChoiceType
    {
        
        /// <remarks/>
        URNIdentifikator,
        
        /// <remarks/>
        UUIDIdentifikator,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UuidLabelInputType : UnikIdType
    {
        
        private string labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public enum AktoerTypeKodeType
    {
        
        /// <remarks/>
        Organisation,
        
        /// <remarks/>
        OrganisationEnhed,
        
        /// <remarks/>
        OrganisationFunktion,
        
        /// <remarks/>
        Bruger,
        
        /// <remarks/>
        ItSystem,
        
        /// <remarks/>
        Interessefaellesskab,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegRegistreringType
    {
        
        private TidspunktType fraTidspunktField;
        
        private TidspunktType tilTidspunktField;
        
        private LivscyklusKodeType livscyklusKodeField;
        
        private bool livscyklusKodeFieldSpecified;
        
        private UnikIdType brugerRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType TilTidspunkt
        {
            get
            {
                return this.tilTidspunktField;
            }
            set
            {
                this.tilTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LivscyklusKodeType LivscyklusKode
        {
            get
            {
                return this.livscyklusKodeField;
            }
            set
            {
                this.livscyklusKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LivscyklusKodeSpecified
        {
            get
            {
                return this.livscyklusKodeFieldSpecified;
            }
            set
            {
                this.livscyklusKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public UnikIdType BrugerRef
        {
            get
            {
                return this.brugerRefField;
            }
            set
            {
                this.brugerRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public enum LivscyklusKodeType
    {
        
        /// <remarks/>
        Opstaaet,
        
        /// <remarks/>
        Importeret,
        
        /// <remarks/>
        Passiveret,
        
        /// <remarks/>
        Slettet,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoegInputType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegInputType
    {
        
        private string foersteResultatReferenceField;
        
        private string maksimalAntalKvantitetField;
        
        private SoegRegistreringType soegRegistreringField;
        
        private SoegVirkningType soegVirkningField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string FoersteResultatReference
        {
            get
            {
                return this.foersteResultatReferenceField;
            }
            set
            {
                this.foersteResultatReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string MaksimalAntalKvantitet
        {
            get
            {
                return this.maksimalAntalKvantitetField;
            }
            set
            {
                this.maksimalAntalKvantitetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SoegRegistreringType SoegRegistrering
        {
            get
            {
                return this.soegRegistreringField;
            }
            set
            {
                this.soegRegistreringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SoegVirkningType SoegVirkning
        {
            get
            {
                return this.soegVirkningField;
            }
            set
            {
                this.soegVirkningField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoegInputType", Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/")]
    public partial class SoegInputType1 : SoegInputType
    {
        
        private EgenskabType[] attributListeField;
        
        private TilstandListeType tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TilstandListeType TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/")]
    public partial class EgenskabType
    {
        
        private VirkningType virkningField;
        
        private string brugervendtNoegleTekstField;
        
        private string cVRNummerTekstField;
        
        private string sENummerTekstField;
        
        private string pNummerTekstField;
        
        private string navnTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=0)]
        public VirkningType Virkning
        {
            get
            {
                return this.virkningField;
            }
            set
            {
                this.virkningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=1)]
        public string BrugervendtNoegleTekst
        {
            get
            {
                return this.brugervendtNoegleTekstField;
            }
            set
            {
                this.brugervendtNoegleTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CVR-NummerTekst", Namespace="urn:oio:sts:6", Order=2)]
        public string CVRNummerTekst
        {
            get
            {
                return this.cVRNummerTekstField;
            }
            set
            {
                this.cVRNummerTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SE-NummerTekst", Namespace="urn:oio:sts:6", Order=3)]
        public string SENummerTekst
        {
            get
            {
                return this.sENummerTekstField;
            }
            set
            {
                this.sENummerTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("P-NummerTekst", Namespace="urn:oio:sts:6", Order=4)]
        public string PNummerTekst
        {
            get
            {
                return this.pNummerTekstField;
            }
            set
            {
                this.pNummerTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sts:6", Order=5)]
        public string NavnTekst
        {
            get
            {
                return this.navnTekstField;
            }
            set
            {
                this.navnTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class VirkningType
    {
        
        private TidspunktType fraTidspunktField;
        
        private TidspunktType tilTidspunktField;
        
        private UnikIdType aktoerRefField;
        
        private AktoerTypeKodeType aktoerTypeKodeField;
        
        private bool aktoerTypeKodeFieldSpecified;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType TilTidspunkt
        {
            get
            {
                return this.tilTidspunktField;
            }
            set
            {
                this.tilTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UnikIdType AktoerRef
        {
            get
            {
                return this.aktoerRefField;
            }
            set
            {
                this.aktoerRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AktoerTypeKodeType AktoerTypeKode
        {
            get
            {
                return this.aktoerTypeKodeField;
            }
            set
            {
                this.aktoerTypeKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AktoerTypeKodeSpecified
        {
            get
            {
                return this.aktoerTypeKodeFieldSpecified;
            }
            set
            {
                this.aktoerTypeKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/")]
    public partial class TilstandListeType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/")]
    public partial class RelationListeType
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetInputType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class RetInputType
    {
        
        private string uUIDIdentifikatorField;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RetInputType", Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/")]
    public partial class RetInputType1 : RetInputType
    {
        
        private EgenskabType[] attributListeField;
        
        private TilstandListeType tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TilstandListeType TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class LaesInputType
    {
        
        private string uUIDIdentifikatorField;
        
        private TidspunktType virkningFraFilterField;
        
        private TidspunktType virkningTilFilterField;
        
        private TidspunktType registreringFraFilterField;
        
        private TidspunktType registreringTilFilterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType VirkningFraFilter
        {
            get
            {
                return this.virkningFraFilterField;
            }
            set
            {
                this.virkningFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TidspunktType VirkningTilFilter
        {
            get
            {
                return this.virkningTilFilterField;
            }
            set
            {
                this.virkningTilFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TidspunktType RegistreringFraFilter
        {
            get
            {
                return this.registreringFraFilterField;
            }
            set
            {
                this.registreringFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TidspunktType RegistreringTilFilter
        {
            get
            {
                return this.registreringTilFilterField;
            }
            set
            {
                this.registreringTilFilterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UuidNoteInputType
    {
        
        private string uUIDIdentifikatorField;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/")]
    public partial class ImportInputType
    {
        
        private VirksomhedType virksomhedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VirksomhedType Virksomhed
        {
            get
            {
                return this.virksomhedField;
            }
            set
            {
                this.virksomhedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/")]
    public partial class VirksomhedType : PartType
    {
        
        private RegistreringType1[] registreringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registrering", Order=0)]
        public RegistreringType1[] Registrering
        {
            get
            {
                return this.registreringField;
            }
            set
            {
                this.registreringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RegistreringType", Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/")]
    public partial class RegistreringType1 : RegistreringType
    {
        
        private EgenskabType[] attributListeField;
        
        private TilstandListeType tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TilstandListeType TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistreringType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class RegistreringType
    {
        
        private string noteTekstField;
        
        private System.DateTime tidspunktField;
        
        private bool tidspunktFieldSpecified;
        
        private LivscyklusKodeType livscyklusKodeField;
        
        private bool livscyklusKodeFieldSpecified;
        
        private UnikIdType brugerRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Tidspunkt
        {
            get
            {
                return this.tidspunktField;
            }
            set
            {
                this.tidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TidspunktSpecified
        {
            get
            {
                return this.tidspunktFieldSpecified;
            }
            set
            {
                this.tidspunktFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LivscyklusKodeType LivscyklusKode
        {
            get
            {
                return this.livscyklusKodeField;
            }
            set
            {
                this.livscyklusKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LivscyklusKodeSpecified
        {
            get
            {
                return this.livscyklusKodeFieldSpecified;
            }
            set
            {
                this.livscyklusKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public UnikIdType BrugerRef
        {
            get
            {
                return this.brugerRefField;
            }
            set
            {
                this.brugerRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VirksomhedType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sts:part:6")]
    public partial class PartType : SagDokObjektType
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PartType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VirksomhedType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LaesFiltreretOutputType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SagDokObjektType
    {
        
        private string uUIDIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class LaesFiltreretOutputType : SagDokObjektType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/")]
    public partial class FiltreretOejebliksbilledeType
    {
        
        private SagDokObjektType objektTypeField;
        
        private RegistreringType1[] registreringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SagDokObjektType ObjektType
        {
            get
            {
                return this.objektTypeField;
            }
            set
            {
                this.objektTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registrering", Order=1)]
        public RegistreringType1[] Registrering
        {
            get
            {
                return this.registreringField;
            }
            set
            {
                this.registreringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpretOutputType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOutputType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LaesOutputType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class BasicOutputType
    {
        
        private StandardReturType standardReturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StandardReturType StandardRetur
        {
            get
            {
                return this.standardReturField;
            }
            set
            {
                this.standardReturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class OpretOutputType : BasicOutputType
    {
        
        private string uUIDIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/")]
    public partial class ListOutputType : BasicOutputType
    {
        
        private FiltreretOejebliksbilledeType[] filtreretOejebliksbilledeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FiltreretOejebliksbillede", Order=0)]
        public FiltreretOejebliksbilledeType[] FiltreretOejebliksbillede
        {
            get
            {
                return this.filtreretOejebliksbilledeField;
            }
            set
            {
                this.filtreretOejebliksbilledeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/")]
    public partial class LaesOutputType : BasicOutputType
    {
        
        private FiltreretOejebliksbilledeType filtreretOejebliksbilledeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FiltreretOejebliksbilledeType FiltreretOejebliksbillede
        {
            get
            {
                return this.filtreretOejebliksbilledeField;
            }
            set
            {
                this.filtreretOejebliksbilledeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpretInputType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class OpretInputType
    {
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="OpretInputType", Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/")]
    public partial class OpretInputType1 : OpretInputType
    {
        
        private EgenskabType[] attributListeField;
        
        private TilstandListeType tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TilstandListeType TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class opretRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.OpretInputType1 OpretInput;
        
        public opretRequest()
        {
        }
        
        public opretRequest(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.OpretInputType1 OpretInput)
        {
            this.RequestHeader = RequestHeader;
            this.OpretInput = OpretInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class opretResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.OpretOutputType OpretOutput;
        
        public opretResponse()
        {
        }
        
        public opretResponse(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.OpretOutputType OpretOutput)
        {
            this.RequestHeader = RequestHeader;
            this.OpretOutput = OpretOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importerRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.ImportInputType ImportInput;
        
        public importerRequest()
        {
        }
        
        public importerRequest(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.ImportInputType ImportInput)
        {
            this.RequestHeader = RequestHeader;
            this.ImportInput = ImportInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importerResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.BasicOutputType ImportOutput;
        
        public importerResponse()
        {
        }
        
        public importerResponse(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.BasicOutputType ImportOutput)
        {
            this.RequestHeader = RequestHeader;
            this.ImportOutput = ImportOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class passiverRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.UuidNoteInputType PassiverInput;
        
        public passiverRequest()
        {
        }
        
        public passiverRequest(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.UuidNoteInputType PassiverInput)
        {
            this.RequestHeader = RequestHeader;
            this.PassiverInput = PassiverInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class passiverResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.BasicOutputType PassiverOutput;
        
        public passiverResponse()
        {
        }
        
        public passiverResponse(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.BasicOutputType PassiverOutput)
        {
            this.RequestHeader = RequestHeader;
            this.PassiverOutput = PassiverOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class laesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.LaesInputType LaesInput;
        
        public laesRequest()
        {
        }
        
        public laesRequest(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.LaesInputType LaesInput)
        {
            this.RequestHeader = RequestHeader;
            this.LaesInput = LaesInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class laesResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.LaesOutputType LaesOutput;
        
        public laesResponse()
        {
        }
        
        public laesResponse(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.LaesOutputType LaesOutput)
        {
            this.RequestHeader = RequestHeader;
            this.LaesOutput = LaesOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.RetInputType1 RetInput;
        
        public retRequest()
        {
        }
        
        public retRequest(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.RetInputType1 RetInput)
        {
            this.RequestHeader = RequestHeader;
            this.RetInput = RetInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.BasicOutputType RetOutput;
        
        public retResponse()
        {
        }
        
        public retResponse(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.BasicOutputType RetOutput)
        {
            this.RequestHeader = RequestHeader;
            this.RetOutput = RetOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sletRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.UuidNoteInputType SletInput;
        
        public sletRequest()
        {
        }
        
        public sletRequest(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.UuidNoteInputType SletInput)
        {
            this.RequestHeader = RequestHeader;
            this.SletInput = SletInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sletResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.BasicOutputType SletOutput;
        
        public sletResponse()
        {
        }
        
        public sletResponse(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.BasicOutputType SletOutput)
        {
            this.RequestHeader = RequestHeader;
            this.SletOutput = SletOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class soegRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.SoegInputType1 SoegInput;
        
        public soegRequest()
        {
        }
        
        public soegRequest(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.SoegInputType1 SoegInput)
        {
            this.RequestHeader = RequestHeader;
            this.SoegInput = SoegInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class soegResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.SoegOutputType SoegOutput;
        
        public soegResponse()
        {
        }
        
        public soegResponse(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.SoegOutputType SoegOutput)
        {
            this.RequestHeader = RequestHeader;
            this.SoegOutput = SoegOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.ListInputType ListInput;
        
        public listRequest()
        {
        }
        
        public listRequest(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.ListInputType ListInput)
        {
            this.RequestHeader = RequestHeader;
            this.ListInput = ListInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/organisation/virksomhed/6/", Order=0)]
        public Kombit.InfrastructureSamples.VirksomhedService.ListOutputType ListOutput;
        
        public listResponse()
        {
        }
        
        public listResponse(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.ListOutputType ListOutput)
        {
            this.RequestHeader = RequestHeader;
            this.ListOutput = ListOutput;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VirksomhedPortTypeChannel : Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VirksomhedPortTypeClient : System.ServiceModel.ClientBase<Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType>, Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType
    {
        
        public VirksomhedPortTypeClient()
        {
        }
        
        public VirksomhedPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public VirksomhedPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public VirksomhedPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public VirksomhedPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kombit.InfrastructureSamples.VirksomhedService.opretResponse Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.opret(Kombit.InfrastructureSamples.VirksomhedService.opretRequest request)
        {
            return base.Channel.opret(request);
        }
        
        public Kombit.InfrastructureSamples.VirksomhedService.OpretOutputType opret(ref Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.OpretInputType1 OpretInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.opretRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.opretRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.OpretInput = OpretInput;
            Kombit.InfrastructureSamples.VirksomhedService.opretResponse retVal = ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).opret(inValue);
            RequestHeader = retVal.RequestHeader;
            return retVal.OpretOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.opretResponse> Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.opretAsync(Kombit.InfrastructureSamples.VirksomhedService.opretRequest request)
        {
            return base.Channel.opretAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.opretResponse> opretAsync(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.OpretInputType1 OpretInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.opretRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.opretRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.OpretInput = OpretInput;
            return ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).opretAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kombit.InfrastructureSamples.VirksomhedService.importerResponse Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.importer(Kombit.InfrastructureSamples.VirksomhedService.importerRequest request)
        {
            return base.Channel.importer(request);
        }
        
        public Kombit.InfrastructureSamples.VirksomhedService.BasicOutputType importer(ref Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.ImportInputType ImportInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.importerRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.importerRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.ImportInput = ImportInput;
            Kombit.InfrastructureSamples.VirksomhedService.importerResponse retVal = ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).importer(inValue);
            RequestHeader = retVal.RequestHeader;
            return retVal.ImportOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.importerResponse> Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.importerAsync(Kombit.InfrastructureSamples.VirksomhedService.importerRequest request)
        {
            return base.Channel.importerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.importerResponse> importerAsync(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.ImportInputType ImportInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.importerRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.importerRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.ImportInput = ImportInput;
            return ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).importerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kombit.InfrastructureSamples.VirksomhedService.passiverResponse Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.passiver(Kombit.InfrastructureSamples.VirksomhedService.passiverRequest request)
        {
            return base.Channel.passiver(request);
        }
        
        public Kombit.InfrastructureSamples.VirksomhedService.BasicOutputType passiver(ref Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.UuidNoteInputType PassiverInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.passiverRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.passiverRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.PassiverInput = PassiverInput;
            Kombit.InfrastructureSamples.VirksomhedService.passiverResponse retVal = ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).passiver(inValue);
            RequestHeader = retVal.RequestHeader;
            return retVal.PassiverOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.passiverResponse> Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.passiverAsync(Kombit.InfrastructureSamples.VirksomhedService.passiverRequest request)
        {
            return base.Channel.passiverAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.passiverResponse> passiverAsync(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.UuidNoteInputType PassiverInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.passiverRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.passiverRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.PassiverInput = PassiverInput;
            return ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).passiverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kombit.InfrastructureSamples.VirksomhedService.laesResponse Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.laes(Kombit.InfrastructureSamples.VirksomhedService.laesRequest request)
        {
            return base.Channel.laes(request);
        }
        
        public Kombit.InfrastructureSamples.VirksomhedService.LaesOutputType laes(ref Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.LaesInputType LaesInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.laesRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.laesRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.LaesInput = LaesInput;
            Kombit.InfrastructureSamples.VirksomhedService.laesResponse retVal = ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).laes(inValue);
            RequestHeader = retVal.RequestHeader;
            return retVal.LaesOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.laesResponse> Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.laesAsync(Kombit.InfrastructureSamples.VirksomhedService.laesRequest request)
        {
            return base.Channel.laesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.laesResponse> laesAsync(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.LaesInputType LaesInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.laesRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.laesRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.LaesInput = LaesInput;
            return ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).laesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kombit.InfrastructureSamples.VirksomhedService.retResponse Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.ret(Kombit.InfrastructureSamples.VirksomhedService.retRequest request)
        {
            return base.Channel.ret(request);
        }
        
        public Kombit.InfrastructureSamples.VirksomhedService.BasicOutputType ret(ref Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.RetInputType1 RetInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.retRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.retRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.RetInput = RetInput;
            Kombit.InfrastructureSamples.VirksomhedService.retResponse retVal = ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).ret(inValue);
            RequestHeader = retVal.RequestHeader;
            return retVal.RetOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.retResponse> Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.retAsync(Kombit.InfrastructureSamples.VirksomhedService.retRequest request)
        {
            return base.Channel.retAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.retResponse> retAsync(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.RetInputType1 RetInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.retRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.retRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.RetInput = RetInput;
            return ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).retAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kombit.InfrastructureSamples.VirksomhedService.sletResponse Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.slet(Kombit.InfrastructureSamples.VirksomhedService.sletRequest request)
        {
            return base.Channel.slet(request);
        }
        
        public Kombit.InfrastructureSamples.VirksomhedService.BasicOutputType slet(ref Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.UuidNoteInputType SletInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.sletRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.sletRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.SletInput = SletInput;
            Kombit.InfrastructureSamples.VirksomhedService.sletResponse retVal = ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).slet(inValue);
            RequestHeader = retVal.RequestHeader;
            return retVal.SletOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.sletResponse> Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.sletAsync(Kombit.InfrastructureSamples.VirksomhedService.sletRequest request)
        {
            return base.Channel.sletAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.sletResponse> sletAsync(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.UuidNoteInputType SletInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.sletRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.sletRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.SletInput = SletInput;
            return ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).sletAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kombit.InfrastructureSamples.VirksomhedService.soegResponse Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.soeg(Kombit.InfrastructureSamples.VirksomhedService.soegRequest request)
        {
            return base.Channel.soeg(request);
        }
        
        public Kombit.InfrastructureSamples.VirksomhedService.SoegOutputType soeg(ref Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.SoegInputType1 SoegInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.soegRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.soegRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.SoegInput = SoegInput;
            Kombit.InfrastructureSamples.VirksomhedService.soegResponse retVal = ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).soeg(inValue);
            RequestHeader = retVal.RequestHeader;
            return retVal.SoegOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.soegResponse> Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.soegAsync(Kombit.InfrastructureSamples.VirksomhedService.soegRequest request)
        {
            return base.Channel.soegAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.soegResponse> soegAsync(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.SoegInputType1 SoegInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.soegRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.soegRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.SoegInput = SoegInput;
            return ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).soegAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kombit.InfrastructureSamples.VirksomhedService.listResponse Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.list(Kombit.InfrastructureSamples.VirksomhedService.listRequest request)
        {
            return base.Channel.list(request);
        }
        
        public Kombit.InfrastructureSamples.VirksomhedService.ListOutputType list(ref Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.ListInputType ListInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.listRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.listRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.ListInput = ListInput;
            Kombit.InfrastructureSamples.VirksomhedService.listResponse retVal = ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).list(inValue);
            RequestHeader = retVal.RequestHeader;
            return retVal.ListOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.listResponse> Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType.listAsync(Kombit.InfrastructureSamples.VirksomhedService.listRequest request)
        {
            return base.Channel.listAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.InfrastructureSamples.VirksomhedService.listResponse> listAsync(Kombit.InfrastructureSamples.VirksomhedService.RequestHeaderType RequestHeader, Kombit.InfrastructureSamples.VirksomhedService.ListInputType ListInput)
        {
            Kombit.InfrastructureSamples.VirksomhedService.listRequest inValue = new Kombit.InfrastructureSamples.VirksomhedService.listRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.ListInput = ListInput;
            return ((Kombit.InfrastructureSamples.VirksomhedService.VirksomhedPortType)(this)).listAsync(inValue);
        }
    }
}
