// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Text : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Text));
        
        string IMigrationMetadata.Id
        {
            get { return "201402241313065_Text"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
