// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OptionEntitytobaseclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OptionEntitytobaseclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201609301133049_Option Entity to base class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
