// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatedadviceobjecttobemoregeneric : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedadviceobjecttobemoregeneric));
        
        string IMigrationMetadata.Id
        {
            get { return "201611250911210_updated advice object to be more generic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
