// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class externalreferencesaddedtoitsystemusagesandremovedfromitsystem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(externalreferencesaddedtoitsystemusagesandremovedfromitsystem));
        
        string IMigrationMetadata.Id
        {
            get { return "201611140951353_external references added to it-system-usages and removed from it-system"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
