namespace Infrastructure.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class referenceaddedtoObjects : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.ItSystemUsage", "ReferenceId", c => c.Int());
            AddColumn("dbo.ItContract", "ReferenceId", c => c.Int());
            AddColumn("dbo.ItProject", "ReferenceId", c => c.Int());
            CreateIndex("dbo.ItSystemUsage", "ReferenceId");
            CreateIndex("dbo.ItContract", "ReferenceId");
            CreateIndex("dbo.ItProject", "ReferenceId");
            AddForeignKey("dbo.ItProject", "ReferenceId", "dbo.ExternalReferences", "Id");
            AddForeignKey("dbo.ItContract", "ReferenceId", "dbo.ExternalReferences", "Id");
            AddForeignKey("dbo.ItSystemUsage", "ReferenceId", "dbo.ExternalReferences", "Id");
            Sql("INSERT INTO [dbo].ExternalReferences \r\n(ItContract_Id, ExternalReferenceId, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, Esdh, ObjectOwnerId, Title = \'Importeret Esdh reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItContract]\r\nWHERE Esdh NOT LIKE \'%http%\' AND Esdh is NOT null AND Esdh != \'\')\r\n\r\nINSERT INTO [dbo].ExternalReferences \r\n(ItContract_Id, Url, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, Esdh, ObjectOwnerId, Title = \'Importeret Esdh reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItContract]\r\nWHERE Esdh LIKE \'%http%\' AND Esdh is NOT null AND Esdh != \'\')\r\n\r\nINSERT INTO [dbo].ExternalReferences \r\n(ItContract_Id, ExternalReferenceId, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, Folder, ObjectOwnerId, Title = \'Importeret Mappe reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItContract]\r\nWHERE Folder NOT LIKE \'%http%\' AND Folder is NOT null AND Folder != \'\')\r\n\r\nINSERT INTO [dbo].ExternalReferences \r\n(ItContract_Id, Url, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, Folder, ObjectOwnerId, Title = \'Importeret Mappe reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItContract]\r\nWHERE Folder LIKE \'%http%\' AND Folder is NOT null AND Folder != \'\')");
            Sql("INSERT INTO [dbo].ExternalReferences \r\n(ItProject_Id, ExternalReferenceId, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, Esdh, ObjectOwnerId, Title = \'Importeret Esdh reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItProject]\r\nWHERE Esdh NOT LIKE \'%http%\' AND Esdh is NOT null AND Esdh != \'\')\r\n\r\nINSERT INTO [dbo].ExternalReferences \r\n(ItProject_Id, Url, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, Esdh, ObjectOwnerId, Title = \'Importeret Esdh reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItProject]\r\nWHERE Esdh LIKE \'%http%\' AND Esdh is NOT null AND Esdh != \'\')\r\n\r\nINSERT INTO [dbo].ExternalReferences \r\n(ItProject_Id, ExternalReferenceId, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, Folder, ObjectOwnerId, Title = \'Importeret Mappe reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItProject]\r\nWHERE Folder NOT LIKE \'%http%\' AND Folder is NOT null AND Folder != \'\')\r\n\r\nINSERT INTO [dbo].ExternalReferences \r\n(ItProject_Id, Url, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, Folder, ObjectOwnerId, Title = \'Importeret Mappe reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItProject]\r\nWHERE Folder LIKE \'%http%\' AND Folder is NOT null AND Folder != \'\')\r\n\r\nINSERT INTO [dbo].ExternalReferences \r\n(ItProject_Id, ExternalReferenceId, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, Cmdb, ObjectOwnerId, Title = \'Importeret Cmdb reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItProject]\r\nWHERE Cmdb NOT LIKE \'%http%\' AND Cmdb is NOT null AND Cmdb != \'\')\r\n\r\nINSERT INTO [dbo].ExternalReferences \r\n(ItProject_Id, Url, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, Cmdb, ObjectOwnerId, Title = \'Importeret Cmdb reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItProject]\r\nWHERE Cmdb LIKE \'%http%\' AND Cmdb is NOT null AND Cmdb != \'\')\r\n");
            Sql("INSERT INTO [dbo].ExternalReferences \r\n(ItSystemUsage_Id, ExternalReferenceId, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, EsdhRef, ObjectOwnerId, Title = \'Importeret Esdh reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItSystemUsage]\r\nWHERE EsdhRef NOT LIKE \'%http%\' AND EsdhRef is NOT null AND EsdhRef != \'\')\r\n\r\nINSERT INTO [dbo].ExternalReferences \r\n(ItSystemUsage_Id, Url, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, EsdhRef, ObjectOwnerId, Title = \'Importeret Esdh reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItSystemUsage]\r\nWHERE EsdhRef LIKE \'%http%\' AND EsdhRef is NOT null AND EsdhRef != \'\')\r\n\r\nINSERT INTO [dbo].ExternalReferences \r\n(ItSystemUsage_Id, ExternalReferenceId, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, DirectoryOrUrlRef, ObjectOwnerId, Title = \'Importeret Mappe reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItSystemUsage]\r\nWHERE DirectoryOrUrlRef NOT LIKE \'%http%\' AND DirectoryOrUrlRef is NOT null AND DirectoryOrUrlRef != \'\')\r\n\r\nINSERT INTO [dbo].ExternalReferences \r\n(ItSystemUsage_Id, Url, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, DirectoryOrUrlRef, ObjectOwnerId, Title = \'Importeret Mappe reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItSystemUsage]\r\nWHERE DirectoryOrUrlRef LIKE \'%http%\' AND DirectoryOrUrlRef is NOT null AND DirectoryOrUrlRef != \'\')\r\n\r\nINSERT INTO [dbo].ExternalReferences \r\n(ItSystemUsage_Id, ExternalReferenceId, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, CmdbRef, ObjectOwnerId, Title = \'Importeret Cmdb reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItSystemUsage]\r\nWHERE CmdbRef NOT LIKE \'%http%\' AND CmdbRef is NOT null AND CmdbRef != \'\')\r\n\r\nINSERT INTO [dbo].ExternalReferences \r\n(ItSystemUsage_Id, Url, ObjectOwnerId, Title, Display, LastChanged, Created)\r\n(SELECT Id, CmdbRef, ObjectOwnerId, Title = \'Importeret Cmdb reference\', Display = 0, LastChanged = GETDATE(), Created = LastChanged FROM [dbo].[ItSystemUsage]\r\nWHERE CmdbRef LIKE \'%http%\' AND CmdbRef is NOT null AND CmdbRef != \'\')\r\n");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.ItSystemUsage", "ReferenceId", "dbo.ExternalReferences");
            DropForeignKey("dbo.ItContract", "ReferenceId", "dbo.ExternalReferences");
            DropForeignKey("dbo.ItProject", "ReferenceId", "dbo.ExternalReferences");
            DropIndex("dbo.ItProject", new[] { "ReferenceId" });
            DropIndex("dbo.ItContract", new[] { "ReferenceId" });
            DropIndex("dbo.ItSystemUsage", new[] { "ReferenceId" });
            DropColumn("dbo.ItProject", "ReferenceId");
            DropColumn("dbo.ItContract", "ReferenceId");
            DropColumn("dbo.ItSystemUsage", "ReferenceId");
        }
    }
}
