// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedrestofthelocaloptions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedrestofthelocaloptions));
        
        string IMigrationMetadata.Id
        {
            get { return "201610152053249_Added rest of the local options"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
