// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OS2Kitos1280_GDPRItSystemUsagesCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OS2Kitos1280_GDPRItSystemUsagesCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201801181059224_OS2Kitos-1280_GDPRItSystemUsagesCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
