// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1280_GDPRSystemUsage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1280_GDPRSystemUsage));
        
        string IMigrationMetadata.Id
        {
            get { return "201801191413299_1280_GDPRSystemUsage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
