// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class KITOS1267_mergeAndNameing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KITOS1267_mergeAndNameing));
        
        string IMigrationMetadata.Id
        {
            get { return "201802060833158_KITOS-1267_mergeAndNameing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
