// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nameaddedtodataprotectionadvisoranddataResponsibleonorganization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nameaddedtodataprotectionadvisoranddataResponsibleonorganization));
        
        string IMigrationMetadata.Id
        {
            get { return "201802011451139_name added to dataprotectionadvisor and dataResponsible on organization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
