// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Dpr_Dqa_Processors_And_Concluded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dpr_Dqa_Processors_And_Concluded));
        
        string IMigrationMetadata.Id
        {
            get { return "202009280554135_Dpr_Dqa_Processors_And_Concluded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
