// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TaskRefCharLimitAndIndexOnTaskKeyIndexOnUuid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaskRefCharLimitAndIndexOnTaskKeyIndexOnUuid));
        
        string IMigrationMetadata.Id
        {
            get { return "202001171203234_TaskRef-Char-Limit-And-Index-On-TaskKey-Index-On-Uuid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
