// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TaskRef_Remove_AccessModifier : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaskRef_Remove_AccessModifier));
        
        string IMigrationMetadata.Id
        {
            get { return "202001150841034_TaskRef_Remove_AccessModifier"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
