// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Redefine_SystemRelation_Ref : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Redefine_SystemRelation_Ref));
        
        string IMigrationMetadata.Id
        {
            get { return "202001291318103_Redefine_SystemRelation_Ref"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
