// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Local_Admin_Toggle_DataProcessingAgreement_Overview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Local_Admin_Toggle_DataProcessingAgreement_Overview));
        
        string IMigrationMetadata.Id
        {
            get { return "202009020656156_Local_Admin_Toggle_DataProcessingAgreement_Overview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
