// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GDPR_Fields_Nullable_Changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GDPR_Fields_Nullable_Changes));
        
        string IMigrationMetadata.Id
        {
            get { return "202003131005236_GDPR_Fields_Nullable_Changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
