// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Introduce_Uuid_User_BusinessType_ItSystem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Introduce_Uuid_User_BusinessType_ItSystem));
        
        string IMigrationMetadata.Id
        {
            get { return "202106140356218_Introduce_Uuid_User_BusinessType_ItSystem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
