// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OrganizationUnit_Add_UUID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrganizationUnit_Add_UUID));
        
        string IMigrationMetadata.Id
        {
            get { return "202107050858226_OrganizationUnit_Add_UUID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
