// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Contract_Remove_DataHandler : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Contract_Remove_DataHandler));
        
        string IMigrationMetadata.Id
        {
            get { return "202104071049413_Contract_Remove_DataHandler"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
