// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class User_Add_StakeholderAccessFlag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Add_StakeholderAccessFlag));
        
        string IMigrationMetadata.Id
        {
            get { return "202106101307490_User_Add_StakeholderAccessFlag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
