// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_OversightDates_To_DPR : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_OversightDates_To_DPR));
        
        string IMigrationMetadata.Id
        {
            get { return "202105141131577_Add_OversightDates_To_DPR"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
