// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LocallyUniqueName_On_Org_Specific_Roots : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LocallyUniqueName_On_Org_Specific_Roots));
        
        string IMigrationMetadata.Id
        {
            get { return "202109010730183_LocallyUniqueName_On_Org_Specific_Roots"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
