// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ITSystemUsage_Remove_DirectoryOrUrlRef : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ITSystemUsage_Remove_DirectoryOrUrlRef));
        
        string IMigrationMetadata.Id
        {
            get { return "202108040928328_ITSystemUsage_Remove_DirectoryOrUrlRef"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
