// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_ItSystemUsageOverviewReadModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_ItSystemUsageOverviewReadModel));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:Infrastructure.DataAccess/Migrations/202104200634182_Add_ItSystemUsageOverviewReadModel.Designer.cs
            get { return "202104200634182_Add_ItSystemUsageOverviewReadModel"; }
=======
            get { return "202104191327400_Add_ItSystemUsageOverviewReadModel"; }
>>>>>>> f27b6dff718f95328188a6015c15367459a45061:Infrastructure.DataAccess/Migrations/202104191327400_Add_ItSystemUsageOverviewReadModel.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
