// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DataProcessingRegistration_Added_Uuid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataProcessingRegistration_Added_Uuid));
        
        string IMigrationMetadata.Id
        {
            get { return "202108101254107_DataProcessingRegistration_Added_Uuid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
