// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Added_sts_subscription_flag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_sts_subscription_flag));
        
        string IMigrationMetadata.Id
        {
            get { return "202211181038597_Added_sts_subscription_flag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
