// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_SystemActive_To_ItSystemUsageOverview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_SystemActive_To_ItSystemUsageOverview));
        
        string IMigrationMetadata.Id
        {
            get { return "202209290951403_Add_SystemActive_To_ItSystemUsageOverview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
