// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Changed_Dpr_SubDataProcessors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changed_Dpr_SubDataProcessors));
        
        string IMigrationMetadata.Id
        {
            get { return "202212210922387_Changed_Dpr_SubDataProcessors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
