// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_itcontract_overview_readmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_itcontract_overview_readmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202209080721502_add_itcontract_overview_readmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
