// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fix_advice_role_relations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_advice_role_relations));
        
        string IMigrationMetadata.Id
        {
            get { return "202208211025538_fix_advice_role_relations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
