// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ItSystemUsageOverviewReadModel_With_Uuids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItSystemUsageOverviewReadModel_With_Uuids));
        
        string IMigrationMetadata.Id
        {
            get { return "202301261218483_ItSystemUsageOverviewReadModel_With_Uuids"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
