// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SystemOverview_Add_Relevant_Org_Units : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SystemOverview_Add_Relevant_Org_Units));
        
        string IMigrationMetadata.Id
        {
            get { return "202302151310396_SystemOverview_Add_Relevant_Org_Units"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
