// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dataprocessingreadmodeluuids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dataprocessingreadmodeluuids));
        
        string IMigrationMetadata.Id
        {
            get { return "202408140755383_data-processing-read-model-uuids"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
