// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Usage_ai_technology_field_as_yesNoUndecided : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Usage_ai_technology_field_as_yesNoUndecided));
        
        string IMigrationMetadata.Id
        {
            get { return "202502111858490_Usage_ai_technology_field_as_yesNoUndecided"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
