// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_dpia_and_businessCritical_fields_to_usage_overview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_dpia_and_businessCritical_fields_to_usage_overview));
        
        string IMigrationMetadata.Id
        {
            get { return "202501231413228_add_dpia_and_businessCritical_fields_to_usage_overview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
